server:
  port: ${PORT:52}

database:
  hostname: localhost
  name: ventas
  port: 3306

spring:
  # ===============================
  # JPA / HIBERNATE
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: ventas-ms

  # ===============================
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.hostname}:${database.port}/${database.name}?autoReconnect=true&serverTimezone=America/Bogota&nullCatalogMeansCurrent=true
    username: root
    password: mypass

registry-service:
  hostname: localhost
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://${registry-service.hostname}:${registry-service.port}/eureka